# Generated by Django 3.0.8 on 2020-07-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'Why Choose us', 'verbose_name_plural': 'Why Choose us'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
